// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace graphqllegacy.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    [Migration("20240531201712_SeedMenusTable")]
    partial class SeedMenusTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A juicy chicken burger with lettuce and cheese",
                            Name = "Classic Burger",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tomato, mozzarella, and basil pizza",
                            Name = "Margherita Pizza",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh garden salad with grilled chicken",
                            Name = "Grilled Chicken Salad",
                            Price = 7.9500000000000002
                        },
                        new
                        {
                            Id = 4,
                            Description = "Creamy Alfredo sauce with fettuccine pasta",
                            Name = "Pasta Alfredo",
                            Price = 12.75
                        },
                        new
                        {
                            Id = 5,
                            Description = "Warm chocolate brownie with ice cream and fudge",
                            Name = "Chocolate Brownie Sundae",
                            Price = 6.9900000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
